version: "2"
services:
    nginx:
        build: ./nginx/
        ports:
            - 80:80
        links:
            - php
        volumes:
            - ./www:/var/www/html
        networks:
            - front-tier
            - back-tier
    php:
        build: ./php/
        links:
            - mysql
        volumes:
            - ./www:/var/www/html
        networks:
            - back-tier

    mysql:
        image: mysql:latest
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project
        networks:
            - back-tier

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql
        networks:
            - back-tier
            - front-tier
networks:
  front-tier:
  back-tier:
